config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'public#index'

  get 'galleries' => 'public#galleries'
  get 'running_club' => 'public#running_club'
  get 'our_club' => 'public#our_club'
  get 'netball_club' => 'public#netball_club'
  get 'calendar' => 'public#calendar'

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/fixture.rb
# Fixture Model
class Fixture < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :sport
end

app/models/gallery.rb
# Gallery Class
class Gallery < ActiveRecord::Base
  belongs_to :tournament
  has_many :gallery_images, dependent: :destroy
  accepts_nested_attributes_for :gallery_images, allow_destroy: :true
end

app/models/gallery_image.rb
include S3ImageConfig
# Gallery Image Class
class GalleryImage < ActiveRecord::Base
  belongs_to :gallery
  has_attached_file :photo,
                styles: {
                  gallery_thumb: '100x100#',
                  gallery_large: '400x400#',
                  gallery_small: '215x215#'
                }

  def self.ransackable_scopes(auth_object = nil)
    [:with_tournament_id]
  end

  scope :with_tournament_id, ->(tournament_id) { Tournament.find(tournament_id).gallery_images }

  validates_attachment :photo, content_type: { :content_type => ['image/jpg', 'image/jpeg', 'image/gif', 'image/png'], message: 'Images must be jpg/jpeg/gif/png format only' },
                               size: { in: 0..2000.kilobytes, message: 'Images should be less than 2 megabytes' }
end

app/models/membership.rb
# Membership Class
class Membership < ActiveRecord::Base
  has_attached_file :file
  validates_attachment :file, content_type: { :content_type => ['application/pdf'], message: 'PDF must be pdf format only' },
                              size: { in: 0..2000.kilobytes, message: "PDF's should be less than 2 megabytes" }
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :number, :subject, :message, :ghost

  validates :name, presence: { message: 'Add your Name' }
  validates :email, presence: { message: 'Add your Email Address' }
  validates :subject, presence: { message: 'Add your Subject' }
  validates :message, presence: { message: 'Add your Message' }
  validate :check_for_spam

  def check_for_spam
    errors.add :ghost if ghost.present?
  end

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :fixtures
  has_many :tournaments
end

app/models/tournament.rb
# Tournament Model
class Tournament < ActiveRecord::Base
  has_many :fixtures, dependent: :destroy
  has_one :gallery, dependent: :destroy
  has_many :gallery_images, through: :gallery
  belongs_to :sport
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, notice: 'Thanks for your message, we will be in touch soon')
    else
      flash.now.alert = 'Error occured'
      render :new
    end
  end
end

app/controllers/public_controller.rb
# Public Controller
class PublicController < ApplicationController
  def index
   # Facebook posts
  	@posts = Post.paginate(page: params[:page], per_page: 3).order('created_time DESC')
    
    # Scrolling Fixtures
    @scrolling_touch_fixtures = Fixture.joins(:sport).where('sports.name = ?', 'Touch').order('fixture_date DESC, kickoff_time DESC').limit(10)

    # All Fixtures
    @fixtures = Fixture.includes(:tournament).order('fixtures.fixture_date DESC, fixtures.kickoff_time DESC')
    @sidebar_touch_fixtures = @fixtures.joins(:sport).where('sports.name = ?', 'Touch').group_by(&:tournament)
    @touch_tournaments = Tournament.joins(:sport).where('sports.name = ?', 'Touch').order('tournaments.tourn_date DESC')
  end

  def galleries
    @tournaments = Tournament.all
    @tournament_year = @tournaments.group_by { |y| y.tourn_date.year }
  end

  def our_club
  end

  def running_club
  end

  def netball_club
    # Scrolling Fixtures
    @scrolling_netball_fixtures = Fixture.joins(:sport).where('sports.name = ?', 'Netball').order('fixture_date DESC, kickoff_time DESC').limit(10)
    @netball_tournaments = Tournament.joins(:sport).where('sports.name = ?', 'Netball').order('tournaments.tourn_date DESC')
    @fixtures = Fixture.includes(:tournament).order('fixtures.fixture_date DESC, fixtures.kickoff_time DESC')
    @sidebar_netball_fixtures = @fixtures.joins(:sport).where('sports.name = ?', 'Netball').group_by(&:tournament)
  end

  def calendar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def date_output(date)
    date.strftime('%e %B %Y') if date
  end

  def time_output(time)
    time.strftime('%H:%M') if time
  end

  def youtube_embed(youtube_url)
  if youtube_url[/youtu\.be\/([^\?]*)/]
    youtube_id = $1
  else
    # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
    youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
    youtube_id = $5
  end

  %Q{<iframe title="YouTube video player" width="583" height="317px" src="https://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
end

  #Get dimensions of Image retrieved from facebook, if too large we are not going to display it
  def image_dimension(url)
    geometry = Paperclip::Geometry.from_file(url)
    width = geometry.width.to_i 
    height = geometry.height.to_i
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/contact/new.html.erb
 <!-- MAIN CONTAINER -->
        <section class="maincontainer">
            <!-- PAGE TITLE -->
            <div class="page-title">Contact Us</div>
            <!-- PAGE CONTAINER -->
            <section class="pagecontainer using-grid">
                <!-- GRID -->
                <div class="grid">
                    <!-- LEFT SIDE -->
                    <div class="unit two-thirds">
                        <h2>Where We Train</h2>
                        <p>If you are interested and want to get involved in Touch Rugby then get in touch with us via the contact form, or find us on <a href="http://www.facebook.com/VarsityVandals" target="_blank">facebook</a> to see when our next training session is.</p>

                        <p>We hope you can join us and look forward to seeing you there.</p>
                        <!-- GOOGLE MAP -->
                       <div id="google-map"></div>
                    </div>
                    <!-- RIGHT SIDE -->
                    <div class="unit one-third">
                        <h3>Contact Details</h3>
                        <ul class="list">
                            <li>
                                <strong>Address:</strong> Pontcanna Fields, CF11 9PP, Cardiff
                            </li>      
                        </ul>
                        <hr/>
                        <h3>Contact Form</h3>
                        <!-- CONTACT FORM -->
                        <%= form_for @message, :url => contact_path, :method => :post, :html => {:id => 'contactForm' } do |f| %>
                  
                        <%= f.text_field :name, :id => 'senderName', :placeholder => 'Name', required: 'required' %>
                        
                        <%= f.text_field :number, :id => 'senderTel', :placeholder => 'Telephone Number', required: 'required' %>
                        
                        <%= f.text_field :email, :id => 'senderEmail', :placeholder => 'Email Address', required: 'required' %>

                        <%= f.text_field :subject, :id => 'senderSubject', :placeholder => 'Subject', required: 'required' %>
                    
                        <%= f.text_area :message, :id => 'message', :rows => 6, :placeholder => 'Message', required: 'required' %>
                   
                        <div class="hidden">
                          <%= f.text_field :ghost, :id => 'inputGhost' %>
                        </div>

                        <%= button_tag 'Send Message', type: 'submit', class: 'button' %>
            
                        <% end %> 
                    </div>
                </div>
            </section>
            <div class="clear"></div>

<script type="text/javascript">
  window.onload = function () {
                  initialize();
                   }
</script>


<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApUO4ajt4kh5KnLE-zJbdmDKrVf7zqsvA">
</script>

<script type="text/javascript">
  function initialize() {
    var mapOptions = {
      center: new google.maps.LatLng(51.491629,-3.207225),
      zoom: 15,
      scrollwheel: false,
      draggable: false,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(document.getElementById("google-map"),mapOptions);

    var marker = new google.maps.Marker({
      position: map.getCenter(),
      map: map,
      title: 'Vandals Training'
    });

    var center;
    function calculateCenter() {
      center = map.getCenter();
    }
    google.maps.event.addDomListener(map, 'idle', function() {
      calculateCenter();
    });
    google.maps.event.addDomListener(window, 'resize', function() {
      map.setCenter(center);
    });
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Varsity Vandals Touch Rugby - Cardiff</title>
  <meta name="description" content="Website for Varsity Vandals Touch Rugby Team Cardiff South Wales">
  <meta name="viewport" content="user-scalable=0,width=device-width,height=device-height,initial-scale=1,maximum-scale=1" />
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <%= render 'shared/alerts' %>
  <%= render 'shared/navbar' %>
    <%= yield %>
  <section class="maincontainer">
  <%= render 'shared/sponsors' %>
  <%= render 'shared/footer' %>
  </section>
</body>
</html>

app/views/shared/_alerts.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
            <footer id="footer">
               
                <div class="clear"></div>
                <!-- COPYRIGHT -->
                <div class="credits">Website built by <a href="http://www.richlewis.co.uk" target="_blank">Richard Lewis</a></div>
                <!-- SOCIAL ICONS -->
                <ul class="social-icons">
                    <li>
                        <%= link_to image_tag('social-icons/facebook.png', class: 'social-icon'), 'http://www.facebook.com/VarsityVandals', target: '_blank' %>
                    </li>
                    <li>
                        <%= link_to image_tag('social-icons/twitter.png', class: 'social-icon'), 'http://twitter.com/VarsityVandals', target: '_blank' %>
                    </li>
                </ul>
            </footer>

app/views/shared/_gallery_images.html.erb
 <div class="resp-tabs-container">
   <% @tournaments.each do |t| %>
     <div>
       <div class="clear"></div>
         <ul class="team-gallery">
          <% t.gallery_images.each do |g| %>
            <li>
              <%= link_to image_tag(g.photo.url(:gallery_large)), g.photo.url(:original), class: 'clb-photo', rel: 'photos' + " " + t.name %> 
            </li>
          <% end %>
        </ul>
        </div>
  <% end %>
</div><!--resp-tabs-container--> 

app/views/shared/_navbar.html.erb
  <!-- HEADER -->
        <header id="header">
            <div class="logo">
              <%= link_to 'Home', root_path, id: 'logo' %>
            </div>
        </header>
        <div class="clear"></div>
        <!-- MAIN MENU -->
        <section id="mainmenu-container">
            <a class="toggleMenu" href="#">Menu</a>
            <nav>
                <ul id="mainmenu">
                    <li>
                        <%= link_to root_path do %>
                            <span>Homepage</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to our_club_path do %>
                            <span>Our Club</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to galleries_path do %>
                            <span>Gallery</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to running_club_path do %>
                            <span>Running Club</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to netball_club_path do %>
                            <span>Netball Club</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to calendar_path do %>
                            <span>Calendar</span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to contact_path do %>
                            <span>Contact</span>
                        <% end %>
                    </li>
                </ul>
            </nav>
        </section>

app/views/shared/_posts.html.erb
<% @posts.each do |p| %>
  <!-- POST -->
  <article class="post">
    <%= image_tag('vandals_fb_profile.png') %>
    <%= link_to 'Varsity Vandals', "https://www.facebook.com/VarsityVandals", target: 'blank' %>
    <%= date_output(p.created_time) %>

      <figure>
        <% if p.video_url? %>
          <%= raw youtube_embed(p.video_url) %>
        <% end %>
      </figure>
      <% if p.message %>
      <p><%= p.message.gsub("\n", "<br>").html_safe %></p>
      <% end %>
        <% if p.description? %>
          <p><%= p.description %></p>
        <% end %>
        <% if p.link? %>
          <%= link_to 'Read More', p.link, target: '_blank' %>
        <% end %>
    </article>
    <hr/>
<% end %>
<%= will_paginate @posts, previous_label: '',  next_label: '', page_links: false %>

app/views/shared/_sponsors.html.erb
<!-- SPONSORS TITLE -->
            <div class="logos-title">Sponsors</div>
            <!-- SPONSORS SLIDER -->
            <section class="sponsor-bg">
            <h2> Would you like to Sponsor Varsity Vandals? If so then please <a href="/contact">Contact Us</a></h2>


            </section>
            <!--<section class="transparent-bg">
                <div id="logos">
                    <div class="slide">
                        <a href="#">
                            <img src="/assets/photos/logo.png" alt="" />
                        </a>
                    </div>
                    <div class="slide">
                        <a href="#">
                            <img src="/assets/photos/logo.png" alt="" />
                        </a>
                    </div>
                    <div class="slide">
                        <a href="#">
                            <img src="/assets/photos/logo.png" alt="" />
                        </a>
                    </div>
                    <div class="slide">
                        <a href="#">
                            <img src="/assets/photos/logo.png" alt="" />
                        </a>
                    </div>
                    <div class="slide">
                        <a href="#">
                            <img src="/assets/photos/logo.png" alt="" />
                        </a>
                    </div>
                </div>
            </section>-->

            